test:
	pycodestyle --show-source --show-pep8 tests/ example/ conway/
	pydocstyle conway/
	pytest --cov=conway tests/*

coverage:
	pytest tests/* --doctest-modules --junitxml=junit/test-results.xml --cov=. --cov-report=xml --cov-report=html

run_build:
	python3 setup.py sdist bdist_wheel

deploy:
	twine upload -r "py-conway" --config-file .pypirc 'dist/*'